# Generated by Django 6.0.7 on 2026-08-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira (₦)'), ('USD', 'US Dollar($)'), ('EUR', 'Euro(£)'), ('GBP', 'British Pound(€)')], default='USD', max_length=3),
        ),
    ]
