# Generated by Django 6.0.7 on 2026-08-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscription_next_renewal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyspendsnapshot',
            name='category_breakdown',
            field=models.JSONField(default=dict),
        ),
    ]
